name: Windows RDP - LocalXpose

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Download and Setup LocalXpose
        run: |
          Write-Host "Downloading LocalXpose..."
          Invoke-WebRequest -Uri "https://api.localxpose.io/api/v2/downloads/loclx-windows-amd64.zip" -OutFile "loclx.zip"
          
          Write-Host "Extracting LocalXpose..."
          Expand-Archive -Path "loclx.zip" -DestinationPath "." -Force
          
          Write-Host "Directory contents after extraction:"
          Get-ChildItem -Path "."
          
          # Verify the executable exists
          if (Test-Path ".\loclx.exe") {
              Write-Host "✓ loclx.exe found successfully"
          } else {
              Write-Host "✗ loclx.exe not found! Checking subdirectories..."
              Get-ChildItem -Path "." -Recurse -Name "*.exe"
              exit 1
          }

      - name: Enable RDP
        run: |
          Write-Host "Enabling RDP..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "✓ RDP enabled successfully"

      - name: Set User Password
        run: |
          Write-Host "Setting user password..."
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!strong123" -Force)
          Write-Host "✓ Password set successfully"

      - name: Start RDP Tunnel
        env:
          LOCX_TOKEN: ${{ secrets.LOCX_TOKEN }}
        run: |
          Write-Host "Starting LocalXpose RDP tunnel..."
          Write-Host "RDP Credentials:"
          Write-Host "  Username: runneradmin"
          Write-Host "  Password: P@ssw0rd!strong123"
          Write-Host ""
          Write-Host "Creating tunnel (this will show the connection URL)..."
          
          # Start tunnel directly with token
          .\loclx.exe tunnel tcp --to 127.0.0.1:3389 --token $env:LOCX_TOKEN
        timeout-minutes: 360
